from collections.abc import Sequence
from typing import Any, Final, Literal

Algorithm = Literal["hmac-sha256", "ed25519", "ml-dsa-44"]
KeyIdType = Literal["key_hash", "public_key"]

ALGORITHMS: Final[tuple[Algorithm, ...]]

class ProtokenError(ValueError): ...
class TokenExpired(ProtokenError): ...
class TokenNotYetValid(ProtokenError): ...
class VerificationFailed(ProtokenError): ...

class Claims:
    def __init__(
        self,
        expires_at: int,
        *,
        not_before: int = 0,
        issued_at: int = 0,
        subject: str = "",
        audience: str = "",
        scopes: Sequence[str] = (),
    ) -> None: ...
    @property
    def expires_at(self) -> int: ...
    @property
    def not_before(self) -> int: ...
    @property
    def issued_at(self) -> int: ...
    @property
    def subject(self) -> str: ...
    @property
    def audience(self) -> str: ...
    @property
    def scopes(self) -> tuple[str, ...]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __eq__(self, other: object) -> bool: ...

class VerifiedToken:
    @property
    def algorithm(self) -> Algorithm: ...
    @property
    def key_id_type(self) -> KeyIdType: ...
    @property
    def key_id(self) -> bytes: ...
    @property
    def claims(self) -> Claims: ...

class UnverifiedToken:
    @property
    def algorithm(self) -> Algorithm: ...
    @property
    def key_id_type(self) -> KeyIdType: ...
    @property
    def key_id(self) -> bytes: ...
    @property
    def claims(self) -> Claims: ...
    @property
    def signature(self) -> bytes: ...

def inspect_token(token: bytes) -> UnverifiedToken: ...

class VerifyingKey:
    @staticmethod
    def from_bytes(data: bytes) -> VerifyingKey: ...
    def to_bytes(self) -> bytes: ...
    @property
    def algorithm(self) -> Algorithm: ...
    @property
    def public_key(self) -> bytes: ...
    def key_hash(self) -> bytes: ...
    def verify(self, token: bytes, now: int | None = None) -> VerifiedToken: ...
    def __eq__(self, other: object) -> bool: ...

class SigningKey:
    @staticmethod
    def generate(algorithm: str = "ed25519") -> SigningKey: ...
    @staticmethod
    def from_bytes(data: bytes) -> SigningKey: ...
    def to_bytes(self) -> bytes: ...
    @property
    def algorithm(self) -> Algorithm: ...
    @property
    def public_key(self) -> bytes: ...
    def verifying_key(self) -> VerifyingKey: ...
    def key_hash(self) -> bytes: ...
    def sign(self, claims: Claims, *, embed_public_key: bool = False) -> bytes: ...
    def verify(self, token: bytes, now: int | None = None) -> VerifiedToken: ...
    def __eq__(self, other: object) -> bool: ...
